// ===== سور القرآن الكريم =====
const SURAHS = [
  {n:1,name:"الفاتحة",en:"Al-Fatiha",verses:7,type:"مكية"},
  {n:2,name:"البقرة",en:"Al-Baqara",verses:286,type:"مدنية"},
  {n:3,name:"آل عمران",en:"Al-Imran",verses:200,type:"مدنية"},
  {n:4,name:"النساء",en:"An-Nisa",verses:176,type:"مدنية"},
  {n:5,name:"المائدة",en:"Al-Ma'ida",verses:120,type:"مدنية"},
  {n:6,name:"الأنعام",en:"Al-An'am",verses:165,type:"مكية"},
  {n:7,name:"الأعراف",en:"Al-A'raf",verses:206,type:"مكية"},
  {n:8,name:"الأنفال",en:"Al-Anfal",verses:75,type:"مدنية"},
  {n:9,name:"التوبة",en:"At-Tawba",verses:129,type:"مدنية"},
  {n:10,name:"يونس",en:"Yunus",verses:109,type:"مكية"},
  {n:11,name:"هود",en:"Hud",verses:123,type:"مكية"},
  {n:12,name:"يوسف",en:"Yusuf",verses:111,type:"مكية"},
  {n:13,name:"الرعد",en:"Ar-Ra'd",verses:43,type:"مدنية"},
  {n:14,name:"إبراهيم",en:"Ibrahim",verses:52,type:"مكية"},
  {n:15,name:"الحجر",en:"Al-Hijr",verses:99,type:"مكية"},
  {n:16,name:"النحل",en:"An-Nahl",verses:128,type:"مكية"},
  {n:17,name:"الإسراء",en:"Al-Isra",verses:111,type:"مكية"},
  {n:18,name:"الكهف",en:"Al-Kahf",verses:110,type:"مكية"},
  {n:19,name:"مريم",en:"Maryam",verses:98,type:"مكية"},
  {n:20,name:"طه",en:"Ta-Ha",verses:135,type:"مكية"},
  {n:21,name:"الأنبياء",en:"Al-Anbiya",verses:112,type:"مكية"},
  {n:22,name:"الحج",en:"Al-Hajj",verses:78,type:"مدنية"},
  {n:23,name:"المؤمنون",en:"Al-Mu'minun",verses:118,type:"مكية"},
  {n:24,name:"النور",en:"An-Nur",verses:64,type:"مدنية"},
  {n:25,name:"الفرقان",en:"Al-Furqan",verses:77,type:"مكية"},
  {n:26,name:"الشعراء",en:"Ash-Shu'ara",verses:227,type:"مكية"},
  {n:27,name:"النمل",en:"An-Naml",verses:93,type:"مكية"},
  {n:28,name:"القصص",en:"Al-Qasas",verses:88,type:"مكية"},
  {n:29,name:"العنكبوت",en:"Al-'Ankabut",verses:69,type:"مكية"},
  {n:30,name:"الروم",en:"Ar-Rum",verses:60,type:"مكية"},
  {n:31,name:"لقمان",en:"Luqman",verses:34,type:"مكية"},
  {n:32,name:"السجدة",en:"As-Sajda",verses:30,type:"مكية"},
  {n:33,name:"الأحزاب",en:"Al-Ahzab",verses:73,type:"مدنية"},
  {n:34,name:"سبأ",en:"Saba",verses:54,type:"مكية"},
  {n:35,name:"فاطر",en:"Fatir",verses:45,type:"مكية"},
  {n:36,name:"يس",en:"Ya-Sin",verses:83,type:"مكية"},
  {n:37,name:"الصافات",en:"As-Saffat",verses:182,type:"مكية"},
  {n:38,name:"ص",en:"Sad",verses:88,type:"مكية"},
  {n:39,name:"الزمر",en:"Az-Zumar",verses:75,type:"مكية"},
  {n:40,name:"غافر",en:"Ghafir",verses:85,type:"مكية"},
  {n:41,name:"فصلت",en:"Fussilat",verses:54,type:"مكية"},
  {n:42,name:"الشورى",en:"Ash-Shura",verses:53,type:"مكية"},
  {n:43,name:"الزخرف",en:"Az-Zukhruf",verses:89,type:"مكية"},
  {n:44,name:"الدخان",en:"Ad-Dukhan",verses:59,type:"مكية"},
  {n:45,name:"الجاثية",en:"Al-Jathiya",verses:37,type:"مكية"},
  {n:46,name:"الأحقاف",en:"Al-Ahqaf",verses:35,type:"مكية"},
  {n:47,name:"محمد",en:"Muhammad",verses:38,type:"مدنية"},
  {n:48,name:"الفتح",en:"Al-Fath",verses:29,type:"مدنية"},
  {n:49,name:"الحجرات",en:"Al-Hujurat",verses:18,type:"مدنية"},
  {n:50,name:"ق",en:"Qaf",verses:45,type:"مكية"},
  {n:51,name:"الذاريات",en:"Adh-Dhariyat",verses:60,type:"مكية"},
  {n:52,name:"الطور",en:"At-Tur",verses:49,type:"مكية"},
  {n:53,name:"النجم",en:"An-Najm",verses:62,type:"مكية"},
  {n:54,name:"القمر",en:"Al-Qamar",verses:55,type:"مكية"},
  {n:55,name:"الرحمن",en:"Ar-Rahman",verses:78,type:"مدنية"},
  {n:56,name:"الواقعة",en:"Al-Waqi'a",verses:96,type:"مكية"},
  {n:57,name:"الحديد",en:"Al-Hadid",verses:29,type:"مدنية"},
  {n:58,name:"المجادلة",en:"Al-Mujadila",verses:22,type:"مدنية"},
  {n:59,name:"الحشر",en:"Al-Hashr",verses:24,type:"مدنية"},
  {n:60,name:"الممتحنة",en:"Al-Mumtahana",verses:13,type:"مدنية"},
  {n:61,name:"الصف",en:"As-Saf",verses:14,type:"مدنية"},
  {n:62,name:"الجمعة",en:"Al-Jumu'a",verses:11,type:"مدنية"},
  {n:63,name:"المنافقون",en:"Al-Munafiqun",verses:11,type:"مدنية"},
  {n:64,name:"التغابن",en:"At-Taghabun",verses:18,type:"مدنية"},
  {n:65,name:"الطلاق",en:"At-Talaq",verses:12,type:"مدنية"},
  {n:66,name:"التحريم",en:"At-Tahrim",verses:12,type:"مدنية"},
  {n:67,name:"الملك",en:"Al-Mulk",verses:30,type:"مكية"},
  {n:68,name:"القلم",en:"Al-Qalam",verses:52,type:"مكية"},
  {n:69,name:"الحاقة",en:"Al-Haqqah",verses:52,type:"مكية"},
  {n:70,name:"المعارج",en:"Al-Ma'arij",verses:44,type:"مكية"},
  {n:71,name:"نوح",en:"Nuh",verses:28,type:"مكية"},
  {n:72,name:"الجن",en:"Al-Jinn",verses:28,type:"مكية"},
  {n:73,name:"المزمل",en:"Al-Muzzammil",verses:20,type:"مكية"},
  {n:74,name:"المدثر",en:"Al-Muddaththir",verses:56,type:"مكية"},
  {n:75,name:"القيامة",en:"Al-Qiyama",verses:40,type:"مكية"},
  {n:76,name:"الإنسان",en:"Al-Insan",verses:31,type:"مدنية"},
  {n:77,name:"المرسلات",en:"Al-Mursalat",verses:50,type:"مكية"},
  {n:78,name:"النبأ",en:"An-Naba",verses:40,type:"مكية"},
  {n:79,name:"النازعات",en:"An-Nazi'at",verses:46,type:"مكية"},
  {n:80,name:"عبس",en:"Abasa",verses:42,type:"مكية"},
  {n:81,name:"التكوير",en:"At-Takwir",verses:29,type:"مكية"},
  {n:82,name:"الانفطار",en:"Al-Infitar",verses:19,type:"مكية"},
  {n:83,name:"المطففين",en:"Al-Mutaffifin",verses:36,type:"مكية"},
  {n:84,name:"الانشقاق",en:"Al-Inshiqaq",verses:25,type:"مكية"},
  {n:85,name:"البروج",en:"Al-Buruj",verses:22,type:"مكية"},
  {n:86,name:"الطارق",en:"At-Tariq",verses:17,type:"مكية"},
  {n:87,name:"الأعلى",en:"Al-A'la",verses:19,type:"مكية"},
  {n:88,name:"الغاشية",en:"Al-Ghashiya",verses:26,type:"مكية"},
  {n:89,name:"الفجر",en:"Al-Fajr",verses:30,type:"مكية"},
  {n:90,name:"البلد",en:"Al-Balad",verses:20,type:"مكية"},
  {n:91,name:"الشمس",en:"Ash-Shams",verses:15,type:"مكية"},
  {n:92,name:"الليل",en:"Al-Layl",verses:21,type:"مكية"},
  {n:93,name:"الضحى",en:"Ad-Duha",verses:11,type:"مكية"},
  {n:94,name:"الشرح",en:"Ash-Sharh",verses:8,type:"مكية"},
  {n:95,name:"التين",en:"At-Tin",verses:8,type:"مكية"},
  {n:96,name:"العلق",en:"Al-Alaq",verses:19,type:"مكية"},
  {n:97,name:"القدر",en:"Al-Qadr",verses:5,type:"مكية"},
  {n:98,name:"البينة",en:"Al-Bayyina",verses:8,type:"مدنية"},
  {n:99,name:"الزلزلة",en:"Az-Zalzala",verses:8,type:"مدنية"},
  {n:100,name:"العاديات",en:"Al-Adiyat",verses:11,type:"مكية"},
  {n:101,name:"القارعة",en:"Al-Qari'a",verses:11,type:"مكية"},
  {n:102,name:"التكاثر",en:"At-Takathur",verses:8,type:"مكية"},
  {n:103,name:"العصر",en:"Al-Asr",verses:3,type:"مكية"},
  {n:104,name:"الهمزة",en:"Al-Humaza",verses:9,type:"مكية"},
  {n:105,name:"الفيل",en:"Al-Fil",verses:5,type:"مكية"},
  {n:106,name:"قريش",en:"Quraysh",verses:4,type:"مكية"},
  {n:107,name:"الماعون",en:"Al-Ma'un",verses:7,type:"مكية"},
  {n:108,name:"الكوثر",en:"Al-Kawthar",verses:3,type:"مكية"},
  {n:109,name:"الكافرون",en:"Al-Kafirun",verses:6,type:"مكية"},
  {n:110,name:"النصر",en:"An-Nasr",verses:3,type:"مدنية"},
  {n:111,name:"المسد",en:"Al-Masad",verses:5,type:"مكية"},
  {n:112,name:"الإخلاص",en:"Al-Ikhlas",verses:4,type:"مكية"},
  {n:113,name:"الفلق",en:"Al-Falaq",verses:5,type:"مكية"},
  {n:114,name:"الناس",en:"An-Nas",verses:6,type:"مكية"}
];

// ===== القراء من موقع surahquran.com =====
const RECITERS = [
  // حرف الألف
  {id:"Imams-alharam",name:"أئمة الحرم",type:"مصحف مشترك"},
  {id:"Ahmed-Al-Huthifi",name:"أحمد الحذيفي",type:"مصحف"},
  {id:"Ahmed-Deban",name:"أحمد ديبان",type:"مصحف كامل"},
  {id:"Ahmed-Trabelsi",name:"أحمد الطرابلسي",type:"مصحف كامل"},
  {id:"Al-Ajmy",name:"أحمد بن علي العجمي",type:"مصحف كامل"},
  {id:"Ahmed-Talib",name:"أحمد طالب حميد",type:"مصحف"},
  {id:"Ahmed-Mohamed-Taher-Sudanese",name:"أحمد محمد طاهر",type:"مصحف كامل"},
  {id:"shahin",name:"أحمد خليل شاهين",type:"مصحف كامل"},
  {id:"maasarawy",name:"أحمد عيسى المعصراوي",type:"مصحف كامل"},
  {id:"ahmad-allahdan",name:"أحمد اللحدان",type:"مصحف كامل"},
  {id:"Ahmad-Alnufais",name:"أحمد النفيس",type:"مصحف كامل"},
  {id:"Ahmad_Naene",name:"أحمد نعينع",type:"مرتل"},
  {id:"Ahmed-Nasr",name:"أحمد نصر",type:"مرتل"},
  {id:"ahmad-aamer",name:"أحمد محمد عامر",type:"مصحف كامل"},
  {id:"alakhdar",name:"إبراهيم الأخضر",type:"مصحف كامل"},
  {id:"Ibrahim-al-Asiri",name:"ابراهيم العسيري",type:"مرتل"},
  {id:"Idris-Abkar",name:"إدريس أبكر",type:"مصحف"},
  {id:"ishak-danish",name:"إسحاق دانيش",type:"مصحف كامل"},
  {id:"akram-alaqimi",name:"أكرم العلاقمي",type:"مصحف كامل"},
  {id:"Ilhan-Tok",name:"إلهان توك",type:"مصحف كامل"},
  {id:"anas",name:"أنس جلهوم",type:"مصحف كامل"},
  {id:"Anas-alemadi",name:"أنس العمادي",type:"مصحف كامل"},
  {id:"Anas-Almiman",name:"أنس الميمان",type:"مصحف كامل"},
  {id:"Amin-Quniwa",name:"الأمين محمد قنيوة",type:"مصحف كامل"},
  {id:"Ayman-Roshdy-Sweed",name:"أيمن سويد",type:"مصحف كامل"},
  // حرف الباء
  {id:"balilah",name:"بندر بليله",type:"مصحف كامل"},
  {id:"badr-alturki",name:"بدر محمد التركي",type:"مصحف كامل"},
  {id:"peshawa",name:"بيشه وا قادر الكردي",type:"مصحف كامل"},
  // حرف التاء
  {id:"Tawfeeq-As-Sayegh",name:"توفيق الصايغ",type:"مصحف كامل"},
  {id:"Tamim-Al-Rimi",name:"تميم الريمي",type:"مصحف كامل"},
  // حرف الجيم
  {id:"Al-Johany",name:"عبدالله عواد الجهني",type:"مصحف كامل"},
  {id:"Jazza-Alswaileh",name:"جزاع الصويلح",type:"مصحف كامل"},
  // حرف الحاء
  {id:"hatem",name:"حاتم فريد الواعر",type:"مصحف كامل"},
  {id:"Hindawi",name:"حجاج الهنداوي",type:"مصحف كامل"},
  {id:"Hamza-Aljazairi",name:"حمزة الجزائري",type:"مصحف كامل"},
  {id:"Hamza-El-Far",name:"حمزة الفار",type:"مصحف كامل"},
  {id:"Hassan-Saleh",name:"حسن محمد صالح",type:"مصحف كامل"},
  {id:"Hassan-Saleh-Warsh",name:"حسن صالح ورش",type:"مصحف كامل"},
  {id:"Hassan-Al-waajidi",name:"حسن الواجدي",type:"مصحف كامل"},
  {id:"Husseini-Azazi",name:"الحسيني العزازي",type:"مصحف كامل"},
  // حرف الخاء
  {id:"aljalil",name:"خالد الجليل",type:"مصحف كامل"},
  {id:"Al-Qahtani",name:"خالد القحطاني",type:"مصحف كامل"},
  {id:"abdulkafi",name:"خالد عبدالكافي",type:"مصحف كامل"},
  {id:"Almohanna",name:"خالد المهنا",type:"مصحف كامل"},
  {id:"khalifa",name:"خليفة الطنيجي",type:"مصحف كامل"},
  {id:"Hafiz-Khalil-Ismail",name:"الحافظ خليل اسماعيل",type:"مصحف كامل"},
  {id:"khalil-alsaghir",name:"خليل الصغير",type:"مصحف كامل"},
  // حرف الدال
  {id:"Daoud-Hamza",name:"داوود حمزة",type:"مصحف كامل"},
  {id:"doukkali",name:"الدوكالي محمد العالم",type:"مصحف كامل"},
  // حرف الراء
  {id:"kordy",name:"رعد محمد الكردي",type:"مصحف"},
  {id:"Rachid-Belalia",name:"رشيد بلعالية",type:"مصحف كامل"},
  {id:"Rachid-Belachia",name:"رشيد بلعشية",type:"مصحف كامل"},
  {id:"Rayyan-Al-Muhaisni",name:"ريان المحيسني",type:"مصحف كامل"},
  // حرف الزاي
  {id:"zaki",name:"زكي داغستاني",type:"مصحف كامل"},
  {id:"zain",name:"الزين محمد أحمد",type:"مصحف كامل"},
  // حرف السين
  {id:"Al-Ghamdi",name:"سعد الغامدي",type:"مصحف كامل"},
  {id:"Al-Shuraim",name:"سعود الشريم",type:"مصحف كامل"},
  {id:"Alkhateeb",name:"سعيد الخطيب",type:"مصحف كامل"},
  {id:"Sahl-Yassin",name:"سهل ياسين",type:"مصحف كامل"},
  // حرف الشين
  {id:"Alshahat_M_Anwar",name:"الشحات محمد أنور",type:"جميع التلاوات"},
  {id:"Shaaban-AlSayyad",name:"شعبان الصياد",type:"مصحف"},
  {id:"Shatri",name:"شيخ أبو بكر الشاطري",type:"مصحف كامل"},
  {id:"Shirazad-Taher",name:"شيرزاد عبدالرحمن طاهر",type:"مصحف كامل"},
  // حرف الصاد
  {id:"Alsahood",name:"صالح الصاهود",type:"مصحف كامل"},
  {id:"Salih-Ahmed-Salih",name:"صالح أحمد صالح",type:"مصحف كامل"},
  {id:"Sadaqat_Ali",name:"صدقات الباكستاني",type:"مصحف كامل"},
  {id:"Salah-Albudair",name:"صلاح البدير",type:"مصحف كامل"},
  {id:"Bukhatir",name:"صلاح بو خاطر",type:"مصحف كامل"},
  {id:"Salah-Jamal",name:"صلاح الجمل",type:"مصحف كامل"},
  {id:"Alhashem",name:"صلاح الهاشم",type:"مصحف كامل"},
  {id:"Salah-Baothman",name:"صلاح باعثمان",type:"مصحف كامل"},
  {id:"soufi",name:"عبدالرشيد صوفي",type:"مصحف كامل"},
  // حرف الطاء
  {id:"Tablawi",name:"محمد الطبلاوي",type:"مصحف كامل"},
  // حرف العين
  {id:"Ammar-Almulla",name:"عمار الملا علي",type:"مرتل"},
  {id:"Adel-Ryan",name:"عادل ريان",type:"مصحف كامل"},
  {id:"AlKalbani",name:"عادل الكلباني",type:"مصحف كامل"},
  {id:"Amer-Kazemi",name:"عامر الكاظمي",type:"مصحف كامل"},
  {id:"Abdul-Bari-Thubaiti",name:"عبدالبارئ الثبيتي",type:"مصحف كامل"},
  {id:"Abdulbaset",name:"عبدالباسط عبدالصمد",type:"مصحف كامل"},
  {id:"Abdulbasitm",name:"عبد الباسط مرتل",type:"مصحف كامل"},
  {id:"Abdulbaset-warsh",name:"عبد الباسط ورش",type:"مصحف كامل"},
  {id:"Abdualhaleem-Hussain",name:"عبد الحليم حسين",type:"مصحف كامل"},
  {id:"Alsudaes",name:"عبدالرحمن السديس",type:"مصحف كامل"},
  {id:"Alsudaes-sh",name:"السديس و الشريم",type:"مصحف كامل"},
  {id:"AbdAlrahman-Al3osy",name:"عبدالرحمن العوسي",type:"مصحف كامل"},
  {id:"Almajed",name:"عبد الرحمن الماجد",type:"مصحف كامل"},
  {id:"Ben-Moussa",name:"عبد الرحمن بنموسى",type:"ورش عن نافع"},
  {id:"Al-Juraidhi",name:"عبد الرحمن الجريذي",type:"مصحف كامل"},
  {id:"Abdelhamid-Ehsain",name:"عبد الحميد احساين",type:"مصحف كامل"},
  {id:"Abdul-Aziz-Al-Ahmad",name:"عبدالعزيز الأحمد",type:"مصحف كامل"},
  {id:"Abdulaziz-Al-Zahrani",name:"عبدالعزيز الزهراني",type:"مصحف"},
  {id:"Abdullah-Al-Khalaf",name:"عبدالله الخلف",type:"مصحف كامل"},
  {id:"Al-Mattrod",name:"عبدالله المطرود",type:"مرتل"},
  {id:"mosa",name:"عبدالله الموسى",type:"جميع التلاوات"},
  {id:"basfar",name:"عبدالله بصفر",type:"مصحف كامل"},
  {id:"khayat",name:"عبدالله خياط",type:"مصحف كامل"},
  {id:"Al-Khulaifi",name:"عبد الله الخليفي",type:"مصحف كامل"},
  {id:"Abdullah-Kamel",name:"عبد الله كامل",type:"مصحف كامل"},
  {id:"Abdul-Razzaq-al-Dulaimi",name:"عبد الرزاق الدليمي",type:"مصحف كامل"},
  {id:"Abdul-Kabeer-Al-Hadidi",name:"عبد الكبير الحديدي",type:"مصحف كامل"},
  {id:"Al-Harthy",name:"عبد المحسن الحارثي",type:"مصحف كامل"},
  {id:"Al-qasim",name:"عبد المحسن القاسم",type:"مصحف كامل"},
  {id:"Abdelmoujib-Benkirane",name:"عبد المجيب بنكيران",type:"مصحف كامل"},
  {id:"Kanakeri",name:"عبدالهادي أحمد كناكري",type:"مصحف كامل"},
  {id:"Abdul-Wadud-Hanif",name:"عبدالودود حنيف",type:"مصحف كامل"},
  {id:"Obaida-Muafaq",name:"عبيدة موفق الكردي",type:"مصحف كامل"},
  {id:"ghassan",name:"غسان الشوربجي",type:"مصحف كامل"},
  {id:"Ali-Alhuthaifi",name:"علي الحذيفي",type:"مصحف كامل"},
  {id:"qalon-Alhuthaifi",name:"الحذيفي برواية قالون",type:"مصحف كامل"},
  {id:"Jaber",name:"علي جابر",type:"مصحف كامل"},
  {id:"Imad-Mansri",name:"عماد المنصري",type:"مصحف كامل"},
  {id:"Al-Qazabri",name:"عمر القزابري",type:"مصحف كامل"},
  {id:"Omar-Hisham",name:"عمر هشام العربي",type:"مصحف كامل"},
  {id:"kouchi",name:"العيون الكوشي",type:"مصحف كامل"},
  // حرف الفاء
  {id:"Fatih-Cholak",name:"فاتح جولاق",type:"مصحف كامل"},
  {id:"Fares",name:"فارس عباد",type:"مصحف كامل"},
  {id:"Alfateh-Alzubair",name:"الفاتح محمد الزبير",type:"مصحف كامل"},
  {id:"Fahad-Almutairi",name:"فهد واصل المطيري",type:"مصحف كامل"},
  {id:"Foad-AlKhamere",name:"فؤاد الخامري",type:"مصحف كامل"},
  {id:"Faisal-AlHajry",name:"فيصل الهاجري",type:"مصحف كامل"},
  // حرف الكاف
  {id:"Karim-Mansouri",name:"كريم منصوري",type:"مصحف كامل"},
  // حرف اللام
  {id:"lahony",name:"مصطفى اللاهوني",type:"مصحف كامل"},
  // حرف الميم
  {id:"Majid-Alzamil",name:"ماجد الزامل",type:"مرتل"},
  {id:"maher",name:"ماهر المعيقلي",type:"مرتل"},
  {id:"Shakhashero",name:"ماهر شخاشيرو",type:"مرتل"},
  {id:"Maher-Alwan",name:"ماهر علوان حدر",type:"حدر سريع"},
  {id:"Mohammad_Ayyub",name:"محمد أيوب",type:"مصحف كامل"},
  {id:"M-Ayyub-traweeh",name:"محمد أيوب التراويح",type:"مصحف كامل"},
  {id:"barrak",name:"محمد البراك",type:"مصحف"},
  {id:"Al-Bakhit",name:"محمد البخيت",type:"مصحف كامل"},
  {id:"Al-Hudayri",name:"محمد الحضيري",type:"مرتل"},
  {id:"Mohammed-Al-Ghazali",name:"محمد الغزالي",type:"مصحف"},
  {id:"Alsubail",name:"محمد السبيل",type:"مصحف كامل"},
  {id:"Al-Kantaoui",name:"محمد الكنتاوي",type:"ورش عن نافع"},
  {id:"allheadan",name:"محمد اللحيدان",type:"مصحف كامل"},
  {id:"Almohisni",name:"محمد المحيسني",type:"مرتل"},
  {id:"Jibrel",name:"محمد جبريل",type:"مصحف كامل"},
  {id:"Hassan",name:"محمد حسان",type:"مصحف كامل"},
  {id:"Mahmoud-Abdel-Hakam",name:"محمود عبد الحكم",type:"مصحف"},
  {id:"Mohamed-Refaat",name:"محمد رفعت",type:"جميع التلاوات"},
  {id:"Muhammad-Faqih",name:"محمد الفقيه",type:"مرتل"},
  {id:"Al-Sharif",name:"محمد رشاد الشريف",type:"جميع التلاوات"},
  {id:"Al-Minshawi",name:"محمد صديق المنشاوي",type:"مصحف كامل"},
  {id:"Al-Minshawi_Mojawwad",name:"المنشاوي مجود",type:"مصحف كامل"},
  {id:"Minshawi-with-kids",name:"المنشاوي مع الأطفال",type:"مصحف كامل"},
  {id:"Al-Hussary",name:"محمود خليل الحصري",type:"مصحف كامل"},
  {id:"Al-Hussary-Mujawwad",name:"الحصري مجود",type:"مصحف كامل"},
  {id:"Al-Hussary-warsh",name:"الحصري برواية ورش",type:"مصحف كامل"},
  {id:"Al-Hussary-qaloon",name:"الحصري برواية قالون",type:"مصحف كامل"},
  {id:"Al-Hosary-children",name:"الحصري المعلم أطفال",type:"مصحف كامل"},
  {id:"Mahmoud-El-Banna",name:"محمود علي البنا",type:"مصحف كامل"},
  {id:"Hadi-Toure",name:"محمد الهادي توري",type:"مصحف كامل"},
  {id:"sayed",name:"محمد سايد",type:"مصحف كامل"},
  {id:"Mohamad-Abdullkarem",name:"محمد عبدالكريم",type:"مصحف كامل"},
  {id:"mohammad-3amer",name:"محمد حسين عامر",type:"مصحف كامل"},
  {id:"Muftah-Saltani",name:"مفتاح السلطني",type:"مصحف كامل"},
  {id:"Alafasi",name:"مشاري العفاسي",type:"مصحف كامل"},
  {id:"mostafa",name:"مصطفى إسماعيل",type:"مصحف كامل"},
  {id:"Mustafa-Ismail-Tajweed",name:"مصطفى اسماعيل تجويد",type:"مصحف كامل"},
  {id:"Mustafa-Gharbi",name:"مصطفى غربي",type:"مصحف كامل"},
  {id:"Mostafa-Raad-Al-Azzawi",name:"مصطفى رعد العزاوي",type:"مصحف كامل"},
  {id:"Mansour",name:"منصور السالمي",type:"مصحف"},
  {id:"Maytham-Tammar",name:"ميثم التمار",type:"مصحف كامل"},
  // حرف النون
  {id:"qattamy",name:"ناصر القطامي",type:"مصحف كامل"},
  {id:"Noreen-Siddiq",name:"نورين محمد صديق",type:"مصحف كامل"},
  {id:"nabil",name:"نبيل الرفاعي",type:"مصحف كامل"},
  {id:"Nima-Al-Hassan",name:"نعمة الحسان",type:"مصحف كامل"},
  // حرف الهاء
  {id:"Hani",name:"هاني الرفاعي",type:"مصحف كامل"},
  {id:"hazzaa",name:"هزاع البلوشي",type:"مصحف"},
  {id:"Hisham-Al-Haraz",name:"هشام الهراز",type:"مصحف"},
  // حرف الواو
  {id:"wadie_alyamni",name:"وديع اليمني",type:"مصحف كامل"},
  // حرف الياء
  {id:"Al-Dosari",name:"ياسر الدوسري",type:"مصحف كامل"},
  {id:"qurashi",name:"ياسر القرشي",type:"مصحف كامل"},
  {id:"yaseen",name:"ياسين الجزائري",type:"مصحف كامل"},
  {id:"Yahya-Hawwa",name:"يحيى حوى",type:"مصحف كامل"},
  {id:"yusuf-nooh",name:"يوسف بن نوح أحمد",type:"مصحف كامل"},
  {id:"Youssef-Ashewaie",name:"يوسف الشويعي",type:"مصحف كامل"}
];

// ===== بناء رابط الصوت =====
function getAudioUrl(reciterId, surahNum) {
  const num = String(surahNum).padStart(3, '0');
  return `https://surahquran.com/sound/${reciterId}/${num}.mp3`;
}

// ===== بناء رابط التحميل =====
function getDownloadUrl(reciterId, surahNum) {
  return getAudioUrl(reciterId, surahNum);
}
